### ISSUE TITLE
Will you make it to produce machine code like c and c++. 

### ISSUE THREAD

**Issue by Neerajsh8851** [vedic-lang/vedic#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PtPrashantTripathi** [comment]
Hi @Neerajsh8851 last year when I have released the version 1.4 it's was just for prototype, since we got this much attention, last from last few months i am currently working on a rust based interpretor for our Vedic Lang.
Hopefully we gonna release it soon
