### ISSUE TITLE
Error when run the code [GLIBC_2.33 Issue]

### ISSUE THREAD

**Issue by amreshpro** [vedic-lang/vedic#25]
-  OS: linux
  
- Error = vedic: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by vedic)
### screenshot  

![Screenshot from 2023-08-17 10-13-31](https://github.com/vedic-lang/vedic-lang.github.io/assets/85226760/6b2f75f3-1ce2-4d39-9477-b1d65509edd4)

**Comment by PtPrashantTripathi** [comment]
Closing the issue since no update was provided by user in last 60 days
