### ISSUE TITLE
वद् → वद

### ISSUE THREAD

**Issue by vvasuki** [vedic-lang/vedic#3]
नमस्करोमि। संस्कृते "वद" इति प्रयोगो वर्तते, न तु "वद्" इति यद्यप्युत्तरभारते हिन्दीभाषायां तादृशम् उच्चारणम्। अतः,  `वद् "वयम् आगताः"` इत्यस्य स्थाने ऽस्यां भाषायां `वद "वयमागताः"` इति स्यात्।

**Comment by PtPrashantTripathi** [comment]
Hi @vvasuki thanks for your input, we will change वद् → वद in the next release.

P.S. : my Sanskrit is not that good, that's why I did this mistek thanks for letting me know

You can ping me https://t.me/ptprashanttripathi if you have any other suggestions
