### ISSUE TITLE
cannot run .veda or .vedic files

### ISSUE THREAD

**Issue by SumeetSinghJi** [vedic-lang/vedic#32]
Hi team just helping out, I love what you do and want to help you grow

EXAMPLE
sumeetsingh@Sumeets-Air-2 examples % vedic namaste.ved
नमस्ते
sumeetsingh@Sumeets-Air-2 examples % vedic namaste.vedic
Invalid file extension. Only .ved files are allowed.
sumeetsingh@Sumeets-Air-2 examples % vedic namaste.veda 
Invalid file extension. Only .ved files are allowed.

SOLUTION: consider removing line in bottom of documentation: https://github.com/vedic-lang/vedic-lang.github.io/blob/main/how-to-use.md

or if it's a planned feature then mention it. I can do either myself if you want.

**Comment by PtPrashantTripathi** [comment]
> Hi team just helping out, I love what you do and want to help you grow
> 
> EXAMPLE
> sumeetsingh@Sumeets-Air-2 examples % vedic namaste.ved
> नमस्ते
> sumeetsingh@Sumeets-Air-2 examples % vedic namaste.vedic
> Invalid file extension. Only .ved files are allowed.
> sumeetsingh@Sumeets-Air-2 examples % vedic namaste.veda 
> Invalid file extension. Only .ved files are allowed.
> 
> SOLUTION: consider removing line in bottom of documentation: https://github.com/vedic-lang/vedic-lang.github.io/blob/main/how-to-use.md
> 
> or if it's a planned feature then mention it. I can do either myself if you want.

This used to work, let me look into the issue, I'll update you about it.

**Comment by PtPrashantTripathi** [comment]
Issue is fixed with latest release 

https://github.com/vedic-lang/vedic/releases/tag/v2.0.6
