### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by SumeetSinghJi** [vedic-lang/vedic#33]
I can fix if you want

- [x] repo description typo it should say: vedic is the world's first complete Sanskrit programming language
- [x] Footer in documentation says "Devloped". It should say “Developed”
- [x] https://vedic-lang.github.io/functions.html - typo - it should say "variables" not "varibals"
- [x] https://vedic-lang.github.io/variables.html#%E0%A4%A4%E0%A4%B0%E0%A5%8D%E0%A4%95-t-tarka-m--logic ## तर्क (t. _tarka_, m.  _logic_)	should be 3 hashtags

**Comment by PtPrashantTripathi** [comment]
@SumeetSinghJi 
Sure please go ahead.

**Comment by SumeetSinghJi** [comment]
I don't have access? may you update the repo description to below please?

I'm not sure if I can sync a repo description from a fork pull request. Never tried.

vedic is the world's first working Sanskrit programming language

**Comment by SumeetSinghJi** [comment]
Can I ask do we have an indentation rule also that you prefer?
e.g. 2 spaces or 4 spaces?


can you also advise what is the best way to add variables together?

e.g. The example program below if I do below it just ads 1 + 1 = 11; not 2.
how can we add numbers together?
सूत्र योग(अ, आ)
{
  मान इ = अ + आ;
  फल अ + आ;
}

# Example addition software written in vedic lang https://vedic-lang.github.io/
#
# Enter a number at both prompts and press enter to see results
# The main function is not required but included for demonstration
# Translations in Sanskrit and English are above each function

# @brief function to return addition results of 2 user input variables
# will return an sanskrit character e.g. १ only if entered in Sanskrit 
# else will return results in Arabic number characters
# TRANSLATION
# sutra yog(a, ā)
# function add(a, ā)
# {
#  phal a + ā;
#  return a + ā;
# }
# @param a the first letter of Sanskrit alphabet is first number to add
# @param ā the second letter of Sanskrit alphabet is the second number to add
# @return results of addition of both avariables
सूत्र योग(अ, आ)
{
  मान इ;
  इ += अ;
  इ += आ;
  फल इ;
}

# sutra sukhya
# function main
सूत्र मुख्य()
{
  # veda(namaste aarambha tantraansh)
  # say(hello beginning software)
  वद("नमस्ते आरम्भ तन्त्रांश");

  # vada(yojayitum prathamam sankhyam pravishantu)
  # say(enter first number to add)
  वद("योजयितुं प्रथमं सङ्ख्यां प्रविशन्तु ");
  # mana a = pathan
  # variable a = reading
  मान अ = पठन();
  # vada(yojayitum dvitiyam sankhyam pravishantu)
  # say(enter second number to add)
  वद("योजयितुं द्वितीयं सङ्ख्यां प्रविशन्तु ");
  # mana ā = pathan
  # variable b  = reading
  मान आ = पठन(); 

  # vada(parinamah a + b)
  # say(result of a + b)
  वद("परिणाम अ + आ = ");

  # vada(yog(अ, आ);
  # say(add(a, b);
  वद(योग(अ,आ));

  # nigram(०)
  # exit(0)
  निर्गम(०);
}

# main
# sukhya
मुख्य();

**Comment by PtPrashantTripathi** [comment]
The pathana function returns string "1"

So that's why

"1"+"1"

= "11"


You have to first convert string to integer 

Open the below link you will understand 

https://vedic-lang.github.io/native_functions.html#2-%E0%A4%85%E0%A4%82%E0%A4%95-ank

**Comment by SumeetSinghJi** [comment]
@PtPrashantTripathi  you are a genius thank you! 

One suggestion as you are the master. Is it possible to have a example program so people actually know this language works? Lots of Reddit comments suggested we have examples.

Since you are now a programming god, I really have to ask what is your preference for text indentation 2 or 4 spaces. Do you have a preference? Stupid question I know, but we have to pick your brain open programming swami haha.

I suggest here: https://vedic-lang.github.io/functions.html

add the below (Feel free to modify it all). I can add it IF you want.


# Example vedic-lang addition program योग.ved (add.ved)

This program prompts a user to enter a number at both prompts to see addition results

The main function is not required but included for demonstration purposes

Translations in Sanskrit and English are above each function


```

# @brief function to return addition results of 2 user input variables
# will return an sanskrit character e.g. १ only if entered in Sanskrit 
#
# sutra yog(a, ā)
# function add(a, ā)
#
# @param a the first letter of Sanskrit alphabet is first number to add
# @param ā the second letter of Sanskrit alphabet is the second number to add
# @return results of addition of both avariables
सूत्र योग(अ, आ)
{
  # a = ank(a)
  # a = convert_string_to_interger(a)
  अ = अंक(अ);
  # man ā = ank(ā)
  # variable a = convert_string_to_interger(a)
  आ = अंक(आ);
  # man parinama = a + ā
  # variable result = a + ā
  मान परिणाम = अ + आ;
  # phal parinama
  # return results
  फल परिणाम;
}

# sutra sukhya
# function main
सूत्र मुख्य()
{
  # veda(namaste aarambha tantraansh)
  # say(hello beginning software)
  वद("नमस्ते आरम्भ तन्त्रांश");

  # vada(yojayitum prathamam sankhyam pravishantu)
  # say(enter first number to add)
  वद("योजयितुं प्रथमं सङ्ख्यां प्रविशन्तु | ");
  # mana a = pathan
  # variable a = reading
  मान अ = पठन();

  # vada(yojayitum dvitiyam sankhyam pravishantu)
  # say(enter second number to add)
  वद("योजयितुं द्वितीयं सङ्ख्यां प्रविशन्तु | ");
  # mana ā = pathan
  # variable b  = reading
  मान आ = पठन(); 

  # vada(parinama a + b)
  # say(result of a + b)
  वद("परिणाम अ + आ = ");

  # vada(yog(अ, आ);
  # say(add(a, b);
  वद(योग(अ,आ));

  # nigram(०)
  # exit(0)
  निर्गम(०);
}

# main
# sukhya
मुख्य();
```
# Results

```zsh
PS C:\Users\testuser\Documents\vedic> vedic योग.ved
नमस्ते आरम्भ तन्त्रांश
योजयितुं प्रथमं सङ्ख्यां प्रविशन्तु | 
१ 
योजयितुं द्वितीयं सङ्ख्यां प्रविशन्तु | 
१
परिणाम अ + आ = 
२
```

**Comment by PtPrashantTripathi** [comment]
https://github.com/vedic-lang/vedic/assets/26687933/a532193b-04cd-4946-9532-8b0af16bfffe

There are some available here

https://vedic-lang.github.io/vedic-ide/

And here https://github.com/vedic-lang/vedic/tree/main/tests

But I did properly commented them 😶

**Comment by SumeetSinghJi** [comment]
That's god damn AMAZING. You are leaving out soo much from your documentation. You have everything already. Thank you I will take some ideas and get back to you what we should add from your Tests.

If I'm bothering you too much just ignore me. I wont break/change anything without your approval swami lol.

**Comment by PtPrashantTripathi** [comment]
No problem brother

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SumeetSinghJi** [comment]
Resolved in PR https://github.com/vedic-lang/vedic-lang.github.io/pull/18
