### ISSUE TITLE
Input function 

### ISSUE THREAD

**Issue by ashu-py** [vedic-lang/vedic#7]
Namaste 
मुझे जानना था कि क्या वेदिक में कोई इनपुट फंक्शन है अगर है तो मुझे बता दीजिए और अगर नहीं तो कृपया कर एक इनपुट फंक्शन बना दीजिए ताकि हम इनपुट ले सके प्रोग्राम मे

**Comment by PtPrashantTripathi** [comment]
Thanks for the suggestion we will include read function in next release

**Comment by ashu-py** [comment]
Well I am waiting for input function .please try to release it as soon as possible

**Comment by PtPrashantTripathi** [comment]
Hi @ashu-py 
We have already added read function in our last [release 2.0.4](https://vedic-lang.github.io/download.html)

[click here to check the पठन सूत्र (read function) example] (https://vedic-lang.github.io/native_functions.html#5-%E0%A4%AA%E0%A4%A0%E0%A4%A8-pathana)


Here is the vedic 2.0.4 download link https://vedic-lang.github.io/download.html

**Comment by ashu-py** [comment]
Thanks a lot for all those new functions✴☺
